//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAFoodBank.MobileAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSettng
    {
        public int Id { get; set; }
        public string ItemKey { get; set; }
        public string ItemValue { get; set; }
    }
}
