//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAFoodBank.MobileAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QAFB_DBEntities : DbContext
    {
        public QAFB_DBEntities()
            : base("name=QAFB_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<ItemPriority> ItemPriorities { get; set; }
        public virtual DbSet<ItemSource> ItemSources { get; set; }
        public virtual DbSet<ItemVendor> ItemVendors { get; set; }
        public virtual DbSet<AppSettng> AppSettngs { get; set; }
    
        public virtual ObjectResult<GetItemSources_Result> GetItemSources(Nullable<int> itemId)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("itemId", itemId) :
                new ObjectParameter("itemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetItemSources_Result>("GetItemSources", itemIdParameter);
        }
    
        public virtual ObjectResult<GetListOfItems_Result> GetListOfItems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListOfItems_Result>("GetListOfItems");
        }
    }
}
